# Generated by Django 6.1.1 on 2026-09-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='media_duration',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='media_size',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='media_url',
        ),
    ]
