# Generated by Django 6.1.1 on 2026-09-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_remove_confession_media_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='details',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('HARASSMENT', 'Harassment'), ('BULLYING', 'Bullying'), ('SPAM', 'Spam'), ('INAPPROPRIATE', 'Inappropriate content'), ('THREAT', 'Threat'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
