# Generated by Django 6.1.1 on 2026-09-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0004_secretsend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REACTION', 'Reaction'), ('COMMENT', 'Comment'), ('SECRET', 'Secret confession')], max_length=20),
        ),
    ]
