# Generated by Django 6.1.1 on 2026-09-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='confession_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('PANORAMA', '360° Panorama')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='confessionmedia',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('PANORAMA', '360° Panorama')], max_length=10),
        ),
    ]
