# Generated by Django 6.1.1 on 2026-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0006_alter_confession_confession_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='confession_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('PANORAMA', 'Panorama')], default='TEXT', max_length=10),
        ),
    ]
